### ISSUE TITLE
Follow conventions in naming things

### ISSUE THREAD

**Issue by acbart** [UD-CISC275-F21/ud-cis-scheduler-team-5#49]
https://github.com/UD-CISC275-F21/ud-cis-scheduler-team-5/blob/c496df557d37f8afa4ad7efec889cfc584dcc7de/src/interfaces/sem.tsx#L2-L7

Use CapitalCamelCase for interfaces. Avoid unnecessary abbreviations and obscure terms. Why `sem` instead of `Semester`?

**Comment by caadams4** [comment]
renamed sem to semester
