### ISSUE TITLE
Incorrect use of mutable state!!!!!

### ISSUE THREAD

**Issue by acbart** [UD-CISC275-F21/ud-cis-scheduler-team-5#51]
https://github.com/UD-CISC275-F21/ud-cis-scheduler-team-5/blob/c496df557d37f8afa4ad7efec889cfc584dcc7de/src/App.tsx#L109

**Comment by caadams4** [comment]
const popSemester:sem[] = currSemesters.map(c=>c);

copied the currSemesters list with map instead of assigning popSemesters directly to currSemesters Value.
